### ISSUE TITLE
Pyguacamole logs

### ISSUE THREAD

**Issue by jaberfat** [mohabusama/pyguacamole#20]
I am using pyguacamole on a django project and I can't see pyguacamole logs. Is there something I should do other than adding pyguacamole to my LOGGING section in setting.py of my project ? or could I be doing it wrong ?

**Comment by mohababdelhameed** [comment]
you could enable the debug logs when initializing the [client](https://github.com/mohabusama/pyguacamole/blob/master/guacamole/client.py#L29).

**Comment by jaberfat** [comment]
Thanks a lot, that didn't work for me, or at least I can't see the logs, so I did this configuration : 
 logging.basicConfig( filename="/mylogpath/guac.log", filemode='a', level=logging.DEBUG ) 
and I passed logger=logging.getLogger() to the constructor of the client.
