### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by lichao0x7cc** [mohabusama/pyguacamole#5]
env python3.5 
![image](https://user-images.githubusercontent.com/13731831/40405694-3d373a64-5e90-11e8-902b-327bbd5f6958.png)

**Comment by lichao0x7cc** [comment]
python2.7 ok

**Comment by mohabusama** [comment]
@lichao0x7cc Thanks for the report. Could you please provide the full stacktrace?

**Comment by lichao0x7cc** [comment]
ERROR:tornado.application:Uncaught exception in /v1/assist
Traceback (most recent call last):
  File "/home/lichao/qcec_venv/lib/python3.5/site-packages/tornado/websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/lichao/qcec_test/qcec_console_ws/api/v1/assist/newapi.py", line 85, in open
    self.guacamole_client.handshake(protocol='ssh', hostname='172.16.103.149', username='root', password='111111', port=22)
  File "/home/lichao/qcec_venv/lib/python3.5/site-packages/guacamole/client.py", line 158, in handshake
    self.send_instruction(Instruction('select', protocol))
  File "/home/lichao/qcec_venv/lib/python3.5/site-packages/guacamole/client.py", line 136, in send_instruction
    return self.send(instruction.encode())
  File "/home/lichao/qcec_venv/lib/python3.5/site-packages/guacamole/client.py", line 122, in send
    self.client.sendall(data)
TypeError: a bytes-like object is required, not 'str'

**Comment by lichao0x7cc** [comment]
i'm resolve it, python 3.5 socket.sendall(bytes,) but python 3.4 socket.sendall(string,)

**Comment by mohabusama** [comment]
Hi @lichao0x7cc , thanks for the details. Will work on a fix and release a new version. Unfortunately, Python3 tests were not accurate and not properly tested.

**Comment by stone2014** [comment]
Hi @mohabusama , thank you your project, it helps too much. But I found when I use py3.6, this project prompts me: "TypeError: a bytes-like object is required, not 'str'". I am trying to modify your code, but it still not work correctly. Can you fix this bug? Thank you very much.

**Comment by mohabusama** [comment]
@stone2014 apologies for the late response 😞  
I will start working on this one today.
